= Spring Cloud Stream Programmable Reactive Transform Processor

A *Spring Cloud Stream* app that takes java code as a parameter and uses it
to configure a Reactor based transform processor. The code supplied must return something that
satisfies `ReactiveProcessor<Object,Object>`.

== Requirements

* Java 8 or Above

== Code Tour

ProgrammableReactiveProcessorApplication:: the Spring Boot Main Application
ProgrammableReactiveProcessorProperties:: defines the configuration properties that are available to the Reactive Transform Processor
  * code: the snippet of java code that defines the Reactive behaviour, for example: `return input -> input.buffer(5).map(list->list.get(0));`
RuntimeJavaCompiler:: a helper service that can run a Java Compiler at runtime
ReactiveTransformer:: the main Reactive processor which delegates to the code compiled at runtime
ProcessorFactory:: the interface implemented by the runtime compiled code

## Building with Maven

```
$> mvn -s .settings.xml clean install
```

## Running the Application

```
$> java -jar target/programmable-reactive-processor-1.0.0.BUILD-SNAPSHOT.jar --code="return m->m.map(s->s.toString().toUpperCase());"
```

## Installing in Spring Cloud Data Flow

```
dataflow> app register --name rx --uri maven://org.springframework.cloud.stream.app:programmable-reactive-processor:1.0.0.BUILD-SNAPSHOT --type processor
```

## Using in a Spring Cloud Data Flow stream definition

Compute the time every second, buffer up 5 of them then pick the first of the 5, discarding the rest:
```
dataflow> stream create --deploy true --name demo --definition "time | rx --code=\"return input -> input.buffer(5).map(list->list.get(0));\" | log"
```

Produce the time in seconds, break it into threes, compute the sum of each group of 3:
```
dataflow> stream create --deploy true --name demo2 --definition "time --dateFormat=ss | rx --code=\"return input -> input.map(s->Integer.valueOf(s.toString())).buffer(3).map(is->{int sum=0;for (int i: is) sum+=i; return sum;});\" | log"
```

## Usage with Flo (COMING SOON!)

With Flo you can type in the Reactive code in a proper editor window, here are some example streams and the
Reactive code you might write in the property editor for the rx module:

1. Compute the time every second, buffer up 5 of them then pick the first of the 5, discarding the rest:

```
time | rx | log
```

```
return input -> input
	.buffer(5)
	.map(list->list.get(0));
```

2. Produce the time in seconds, break it into threes, sum each group of 3: 
```
time --dateFormat=ss | rx | log
```
```
return input -> input
	.map(s->Integer.valueOf(s.toString()))
	.buffer(3)
	.map(is->{int sum=0;for (int i: is) sum+=i; return sum;});
```
